use_frameworks!
inhibit_all_warnings!

target 'TransformableObject_Example' do
  pod 'TransformableObject', :path => '../'

  target 'TransformableObject_Tests' do
    pod 'Quick'
    pod 'Nimble'
  end
end
